---
# Replication Controller for springapp
apiVersion: extensions/v1
kind: ReplicationController
metadata:
  name: spring-controller
spec:
  replicas: 1
  selector:
    app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - image: ananddevlearner11/spring-boot-mongo
        name: springboot
        ports:
        - containerPort: 8080   
