---
# deployment for springapp        
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: ananddevlearner11/spring-boot-mongo
        ports:
        - containerPort: 80
   
