---
# Replication Controller for springapp
apiVersion: v1
kind: Pod
metadata:
  name: spring-controller
spec:
      containers:
      - image: ananddevlearner11/spring-boot-mongo
        name: springboot
   
